name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # 根据需要选择 Node.js 版本

    - name: Install dependencies
      run: |
        cd frontend # 前端目录
        npm install
        cd ../backend # 后端目录
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Run tests
      run: |
        cd frontend
        npm test -- --watchAll=false # 确保测试在 CI 中运行
        cd ../backend
        npm test
