name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # 根据需要选择 Node.js 版本

    - name: Install dependencies
      run: |
        cd hhikr_kanban_frontend # 前端目录
        npm install
        cd ../hhikr_kanban_backend # 后端目录
        npm install

    - name: Build frontend
      run: |
        cd hhikr_kanban_frontend
        npm run build
