name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 设置node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' 

    - name: 安装依赖
      run: |
        cd hhikr_kanban_frontend 
        npm install
        cd ../hhikr_kanban_backend 
        npm install

    - name: 项目打包
      run: |
        cd hhikr_kanban_frontend
        npm run build

    - name: 部署到Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with: 
        branch: gh-pages
        folder: hhikr_kanban_frontend/dist